export default {
  codeHighlight: {
    atrule: 'code-token__attr',
    attr: 'code-token__attr',
    boolean: 'code-token__property',
    builtin: 'code-token__selector',
    cdata: 'code-token__comment',
    char: 'code-token__selector',
    class: 'code-token__function',
    'class-name': 'code-token__function',
    comment: 'code-token__comment',
    constant: 'code-token__property',
    deleted: 'code-token__property',
    doctype: 'code-token__comment',
    entity: 'code-token__operator',
    function: 'code-token__function',
    important: 'code-token__variable',
    inserted: 'code-token__selector',
    keyword: 'code-token__attr',
    namespace: 'code-token__variable',
    number: 'code-token__property',
    operator: 'code-token__operator',
    prolog: 'code-token__comment',
    property: 'code-token__property',
    punctuation: 'code-token__punctuation',
    regex: 'code-token__variable',
    selector: 'code-token__selector',
    string: 'code-token__selector',
    symbol: 'code-token__property',
    tag: 'code-token__property',
    url: 'code-token__operator',
    variable: 'code-token__variable',
  }
}
